# Generated by Django 4.2.2 on 2023-07-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
        migrations.AddField(
            model_name="user",
            name="password1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password2",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
