# Generated by Django 4.2.2 on 2023-07-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pics", "0002_remove_user_password_user_password1_user_password2"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
